version: '3.8'

services:
  academic-research-assistant:
    build: .
    ports:
      - "8502:8502"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-pro}
      - PERFORMANCE_MODE=${PERFORMANCE_MODE:-fast}
    volumes:
      - model_cache:/app/.cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8502/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  model_cache:
